// Generates TypeScript types and server infrastructure from process.yaml.
//
// Requires the gent server to be running (gentctl validate calls it).
//
// Outputs:
//   playground/generated/types.ts   — TypeScript interfaces for all schemas
//   playground/generated/server.ts  — typed Handlers interface + startServer()
//   playground/generated/schema.json — raw SchemaFile for inspection
//
// Usage: bun run playground:generate

import { compile } from "json-schema-to-typescript";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const dir = join(import.meta.dirname, "generated");
const opts = { bannerComment: "", additionalProperties: false };
const repoRoot = join(import.meta.dirname, "../..");
const processYaml = join(import.meta.dirname, "process.yaml");

function toPascalCase(s: string): string {
  return s
    .split(/[_-]/)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

// Run gentctl validate — talks to the gent server and returns inferred schemas.
const result = spawnSync(
  "go",
  [
    "run",
    "./cmd/gentctl",
    "validate",
    "--server",
    "http://localhost:8888",
    "-f",
    processYaml,
  ],
  { cwd: repoRoot, encoding: "utf8" },
);

if (result.status !== 0) {
  throw new Error(`gentctl validate: ${result.stderr.trim()}`);
}

// validate returns []SchemaFile; we're working with a single definition file.
type TaskEntry = {
  input?: object;
  output?: { $ref: string };
  action_type: string;
};
type SchemaFile = {
  process_input?: { $ref: string };
  tasks?: Record<string, TaskEntry>;
  $defs?: Record<string, object>;
};

const schemas = JSON.parse(result.stdout) as SchemaFile[];
const schemaFile = schemas[0];
const {
  process_input: processInput,
  tasks = {},
  $defs: defs = {},
} = schemaFile;

await writeFile(
  join(dir, "schema.json"),
  JSON.stringify(schemaFile, null, 2) + "\n",
);
console.log("Wrote playground/generated/schema.json");

function refDefName(ref: { $ref: string }): string {
  return ref.$ref.replace("#/$defs/", "");
}

// Each named schema is compiled on its own, but its body may contain
// `$ref: #/$defs/...` pointers into sibling defs (e.g. a recursive type the
// engine hoisted to the shared $defs). Re-attach the shared $defs so those
// refs resolve during compilation.
function withDefs(s: object): object {
  return { ...s, $defs: defs };
}

// ─── generate types.ts ────────────────────────────────────────────────────

const typeSections: string[] = [
  "// Auto-generated by playground/codegen.ts — do not edit by hand.",
  "// Re-run `bun run playground:generate` after changing process.yaml.",
  "",
];

if (processInput) {
  const inputDef = defs[refDefName(processInput)];
  if (inputDef)
    typeSections.push(await compile(withDefs(inputDef), "ProcessInput", opts));
}

for (const [id, task] of Object.entries(tasks)) {
  const pascal = toPascalCase(id);

  if (task.input) {
    const inputRef = task.input as { $ref?: string };
    const inputSchema = inputRef.$ref
      ? (defs[refDefName(inputRef as { $ref: string })] ?? task.input)
      : task.input;
    typeSections.push(await compile(withDefs(inputSchema), `${pascal}Input`, opts));
  }

  if (task.output) {
    const defSchema = defs[refDefName(task.output)];
    if (defSchema) {
      typeSections.push(await compile(withDefs(defSchema), `${pascal}Output`, opts));
    }
  }
}

await writeFile(join(dir, "types.ts"), typeSections.join("\n"));
console.log("Generated playground/generated/types.ts");

// ─── generate server.ts ───────────────────────────────────────────────────

function buildServerFile(): string {
  const taskIds = Object.keys(tasks);
  const importedTypes: string[] = [];
  const handlerLines: string[] = [];

  for (const id of taskIds) {
    const pascal = toPascalCase(id);
    const task = tasks[id];
    if (task.action_type !== "rest") {
      continue;
    }
    const inputType = task.input ? `${pascal}Input` : "Record<string, never>";
    const outputType = task.output
      ? `${pascal}Output`
      : "Record<string, unknown>";
    importedTypes.push(inputType);
    if (task.output) importedTypes.push(outputType);
    handlerLines.push(`  ${id}: (ctx: ${inputType}) => Promise<${outputType}>`);
  }

  const schemaEntries = taskIds
    .filter((id) => tasks[id].output)
    .map((id) => {
      const defName = refDefName(tasks[id].output!);
      return `  ${JSON.stringify(id)}: ${JSON.stringify(defs[defName], null, 2).replace(/\n/g, "\n  ")}`;
    })
    .join(",\n");

  const uniqueImports = [...new Set(importedTypes)].join(", ");

  return [
    "// Auto-generated by playground/codegen.ts — do not edit by hand.",
    "// Re-run `bun run playground:generate` after changing process.yaml.",
    "",
    "import { createServer } from 'node:http'",
    "import Ajv from 'ajv'",
    `import type { ${uniqueImports} } from './types.ts'`,
    "",
    "// Transport envelope — mirrors internal/transport/transport.go",
    "interface TaskRequest {",
    "  instance_id: string",
    "  task_id:     string",
    "  data:        unknown",
    "}",
    "",
    "// Implement this in server.ts and pass it to startServer().",
    "export interface Handlers {",
    ...handlerLines,
    "}",
    "",
    "// Output schemas baked in for runtime validation via AJV.",
    "const taskSchemas: Record<string, object> = {",
    schemaEntries,
    "}",
    "",
    "const ajv = new Ajv()",
    "const validators = Object.fromEntries(",
    "  Object.entries(taskSchemas).map(([id, schema]) => [id, ajv.compile(schema)])",
    ")",
    "",
    "export function startServer(handlers: Handlers, port: number): void {",
    "  const server = createServer(async (req, res) => {",
    "    const taskId = new URL(req.url ?? '/', `http://localhost`).pathname.slice(1)",
    "",
    "    if (!(taskId in handlers)) {",
    "      res.writeHead(404, { 'Content-Type': 'application/json' })",
    "      res.end(JSON.stringify({ status: 'error', error: `no handler for task \"${taskId}\"` }))",
    "      return",
    "    }",
    "",
    "    let body = ''",
    "    for await (const chunk of req) body += chunk",
    "    const taskReq: TaskRequest = JSON.parse(body)",
    "    console.log(`→ ${taskId} [${taskReq.instance_id}]`)",
    "",
    "    try {",
    "      const fn = (handlers as unknown as Record<string, (ctx: unknown) => Promise<unknown>>)[taskId]",
    "      const output = await fn(taskReq.data)",
    "      const validate = validators[taskId]",
    "      if (validate && !validate(output)) {",
    "        console.log(`← ${taskId} [schema error]`)",
    "        res.writeHead(500, { 'Content-Type': 'application/json' })",
    "        res.end(JSON.stringify({ error: `output schema violation: ${ajv.errorsText(validate.errors)}` }))",
    "        return",
    "      }",
    "      console.log(`← ${taskId} [ok]`)",
    "      res.writeHead(200, { 'Content-Type': 'application/json' })",
    "      res.end(JSON.stringify(output))",
    "    } catch (err) {",
    "      console.log(`← ${taskId} [error]`)",
    "      res.writeHead(500, { 'Content-Type': 'application/json' })",
    "      res.end(JSON.stringify({ error: String(err) }))",
    "    }",
    "  })",
    "  server.listen(port, () => {",
    "    console.log(`Task server listening on http://localhost:${port}`)",
    "    console.log('Endpoints:', Object.keys(handlers).map(id => `/${id}`).join(', '))",
    "  })",
    "}",
    "",
  ].join("\n");
}

await writeFile(join(dir, "server.ts"), buildServerFile());
console.log("Generated playground/generated/server.ts");
